/*
function multiply(first,second) {
    var product = first * second;
    console.log(product);
}

multiply(true,true);    //1*1 = 1
multiply(true,false);   //1*0 = 0
multiply(3,"hello");    //3*"string" = NaN

var a = Number(0/1); //returns NaN for numbers
console.log(a);
console.log(Math.PI);


var paragraph = "one two three" +
                "four five six" +
                "seven eight nine";
var positiveSearch = "twelve";
var indexOfSearch = paragraph.indexOf(positiveSearch);
console.log(indexOfSearch);         //returns -1 when cant find string in paragraph

var readline = require('readline-sync');
var age = readline.question("asdf");
console.log(age);
//readline = "abc";
var name = readline.question("fdsa");
console.log(name);
//console.log(readline);

const cmPerInch = 2.54;
const inchesPerFoot = 12;
const readline = require('readline-sync');

var feet = parseInt(readline.question("How tall are you in feet (omit inches): "));
var inches = parseInt(readline.question("Enter omitted inches: "));

var totalInches = feet * inchesPerFoot + inches;
var totalCM = totalInches * cmPerInch;

console.log('Centimeters: %f\n', totalCM);

var a = "Don";
var b = 123
console.log(" thie is a test for %s and it is %i",a,b);

var x = 5;
function f() {
    x = 6;
    var x = 11;
    console.log("Within f() x =", x);
}

console.log("Before f: x =", x);
f();
console.log("After f: x =", x);


function adjustGrade(grade) {

    grade -= 5;
    console.log("New grade inside the function: %d", grade);
    return grade;
}
    
var grade = 95;
grade = adjustGrade(grade)
console.log("New grade outside the function: %d", grade);


const readline = require("readline-sync");

var userInput = readline.question("What kind of fruit do you want: ");

userInput = userInput.trim().toLowerCase();
switch (userInput) {
case 'oranges':
console.log('Oranges are $0.59 a pound.');
//break;
case 'apples':
console.log('Apples are $0.32 a pound.');
//break;
default:
console.log('Sorry, we are out of ' + userInput + '.');
}

console.log("Is there anything else you'd like?");

*/

/*
const readline = require("readline-sync");

var userInput = "";
while (true) {

    userInput = readline.question("Enter any fruit: ");
    userInput = userInput.trim().toLowerCase();

    if (userInput === "quit") {
        break;
    }
    switch (userInput) {
        case 'oranges':
            console.log('Oranges are $0.59 a pound.');
            break;
        case 'apples':
            console.log('Apples are $0.32 a pound.');
            break;
        default:
            console.log('Sorry, we are out of ' + userInput + '.');
    }
    console.log("Is there anything else you'd like?");
}

*/

/*
//skips the console.log if divides by 2
var index = 0;
while (index < 10) {
    index += 1;
    if (index % 2 === 0) {
        continue;
    }
    console.log(index);
}
*/

/*
var flippedCoin = true;
if (flippedCoin) {
    var a = 100;
    console.log(a);
} else {
    var b = 100;
    console.log(b);
}
console.log(a);
console.log(b);
*/

//console.log(typeof(1232));

/*
foo();
function foo () {
	console.log("hello");
}
*/

/*
console.log(a);
var a = "hi";
console.log(a);
*/

/*
How do ternary operators work? Answer how they work in a comment,
and then show an example of using a ternary operator and having the result assigned to a variable (let or const is fine). 
Then print out the result of the variable. 
 */

 /* 
Ternary operators work with 3 "parameters"
(a boolean expresstion)? result if true: result if false
 */

 /*
 var input = "Monday";
 let coffee = null;


 //input = "Tuesday";
 let example = (input === "Monday")? coffee = "Yes": coffee = "Maybe not";
 console.log(example);
 //console.log(coffee);
*/

// let arr = [1,2,3,4,5,6,7,8,9];
// console.log(arr.length);


/*
var str = "Random input generated by some thoughtless process.     ";

//1. returns the # of individual characters in string .lenght does not need ()
console.log(str.length);

//2. removes pre and post empty space of a string
console.log(str.trim());

//3. looks for exact copy of search value and 
//returns the index of first instance it.
let searchValue = "process";
console.log(str.indexOf(searchValue));

//4. cuts out str string from position 43 for the next 7 characters
console.log(str.substr(43, 7));

//5. all characters changed to uppercase
console.log(str.toUpperCase());

// 6. concat
console.log(str.concat("More stuff added"));

*/

var testArr =  [45,22,2222,11111,33,200,300];

//sorts by ascii order
//mutates the array
console.log(testArr.sort());

//removes last element of array and returns it
//mutates the array
console.log(testArr.pop());

//adds parameter to the end of the array
//mutates the array
console.log(testArr.push(2019));

//cuts a segment from the array (strating postion , ending position)
//does not mutate the array, unless assigned
console.log(testArr.slice(2,6));

console.log(testArr);


const fs = require("fs");

fs.writeFileSync("log.txt",Logs)